---
rooms:
    living:
        zone: living
        aliases: [living area, living room, family room]
        devices:
            diningmain:
                aliases: [dining room light, dining room main light]
            dininglow: 
                aliases: [dining room chimney light, chimney light, hearth light]
            kitchenmain:
                aliases: [kitchen lights, main kitchen lights]
            kitchenlow:
                aliases: [kitchen low lights, kitchen downlights]
            loungemain:
                aliases: [lounge main light, lounge light]
            loungespot:
                aliases: [lounge spotlights]
            floorlamp
                aliases: [floor lamp]
    kitchen:
        zone: living
        devices:
            kitchenmain:
                aliases: [lights, main lights]
            kitchenlow:
                aliases: [low lights, downlights]
            floorlamp
                aliases: [floor lamp]
    dining:
        zone: living
        aliases: [dining room]
        devices:
            diningmain:
                aliases: [light, main light]
            dininglow: 
                aliases: [chimney light, hearth light]
    lounge:
        zone: living
        aliases: [back lounge, back room]
        devices:
            loungemain:
                aliases: [main light, light]
            loungespot:
                aliases: [spotlights]
            floorlamp
                aliases: [floor lamp]        
    front:
        zone: front
        aliases: [front room, front lounge, office]
    hall:
        zone: common
        aliases: [hallway, entrance, entrance way]
    landing:
        zone: common
        aliases: [middle landing]
    top landing:
        zone: common
        aliases: [loft landing]
